#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config focus_follows_pointer true
bspc config top_padding 32
bspc config border_width 4
bspc config window_gap 8
bspc config focused_border_color "#98c379"
bspc config normal_border_color "#3e4452"
bspc config active_border_color "#e06c75"
bspc config presel_feedback_color "#56b6c2"
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true

# Window rules
bspc rule -r *:*
bspc rule -a Firefox-esr desktop='^2' follow=on focus=on
bspc rule -a Transmission-gtk desktop='^2' follow=on focus=on
bspc rule -a libreoffice desktop='^4' follow=on focus=on
bspc rule -a *:soffice desktop='^4' follow=on focus=on
bspc rule -a Soffice desktop='^4' follow=on focus=on
bspc rule -a libreoffice-writer desktop='^4' follow=on focus=on
bspc rule -a libreoffice-calc desktop='^4' follow=on focus=on
bspc rule -a libreoffice-impress desktop='^4' follow=on focus=on
bspc rule -a Audacious state=floating follow=on focus=on
bspc rule -a Firefox:Places state=floating follow=on focus=on
bspc rule -a mpv state=floating follow=on focus=on

# Bspwm autostart
pkill polybar
polybar top &
xrdb ~/.Xresources
setxkbmap -layout "us,lt,ru" -option "grp:menu_toggle"
dunst &
~/.fehbg
